---
language: ruby
before_install: rm Gemfile.lock || true
sudo: false
cache: bundler
script: bundle exec rake $CHECK
stages:
  - test
  - acceptance
  - build
matrix:
  fast_finish: true
  include:
  - rvm: 2.5.7
    env: PUPPET_VERSION="~> 4.10" CHECK=test
    bundler_args: --without development system_test release
    stage: test
  - rvm: 2.5.7
    env: PUPPET_VERSION="~> 5.0" CHECK=test
    bundler_args: --without development system_test release
    stage: test
  - rvm: 2.5.7
    env: PUPPET_VERSION="~> 5.5" CHECK=test
    bundler_args: --without development system_test release
    stage: test
  - rvm: 2.5.7
    env: PUPPET_VERSION="~> 6.0" CHECK=test
    bundler_args: --without development system_test release
    stage: test
  - rvm: 2.5.7
    dist: trusty
    env: BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=centos-7 CHECK=beaker
    bundler_args: --without development release
    services: docker
    sudo: required
    stage: acceptance
  - rvm: 2.5.7
    dist: trusty
    env: BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=fedora-31 CHECK=beaker
    bundler_args: --without development release
    services: docker
    sudo: required
    stage: acceptance
  - rvm: 2.5.7
    dist: trusty
    env: BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=ubuntu-1804 CHECK=beaker
    bundler_args: --without development release
    services: docker
    sudo: required
    stage: acceptance
  - rvm: 2.5.7
    bundler_args: --without development system_test release
    env: PUPPET_VERSION="~> 5.5" CHECK=build DEPLOY_TO_FORGE=yes
    stage: build

deploy:
  provider: puppetforge
  user: eirikur
  password: $PUPPETFORGE_PASSWORD
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"