language: ruby
before_install: rm Gemfile.lock || true
sudo: false
jobs:
  include:
    - stage: build
      rvm: 2.5.7
      env: PUPPET_VERSION="4.10.11"
      script:
        - bundle exec rake build:pdk
    - stage: test
      rvm: 2.5.7
      env: PUPPET_VERSION="4.10.11"
      script:
        - bundle exec rake test