language: ruby
before_install: rm Gemfile.lock || true
sudo: false
cache: bundler
script: bundle exec rake $CHECK
matrix:
  fast_finish: true
  include:
  - rvm: 2.5.7
    env: PUPPET_VERSION="~> 5.5" PDK_VERSION="~> 1.18" CHECK=build:pdk
    bundler_args: --without development
  - rvm: 2.5.7
    env: PUPPET_VERSION="~> 5.5" PDK_VERSION="~> 1.18" CHECK=test
    bundler_args: --without development
branches:
  only:
  - master
  - /^v\d/
deploy:
  provider: puppetforge
  user: eirikur
  password:
    secure: $PUPPETFORGE_PASSWORD
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true