language: ruby
before_install: rm Gemfile.lock || true
sudo: false
script: bundle exec rake $CHECK
matrix:
  fast_finish: true
  include:
  - rvm: 2.5.7
    env: PUPPET_VERSION="~> 6.17" PDK_VERSION="~> 1.18" CHECK=build:pdk
  - rvm: 2.5.7
    env: PUPPET_VERSION="~> 6.17" PDK_VERSION="~> 1.18" CHECK=test